# configs/main_config.yaml

project_name: "itmo_pfc"
random_state: 42


# ====== ДАННЫЕ ======

data:
  # Названия столбцом
  smiles_col: "canonical_smiles"
  target_col: "pIC50"

  # Директории
  raw_dir: "data/01_raw/"
  processed_dir: "data/02_processed/"
  features_dir: "data/03_features/"

  # Идентификаторы мишеней для скачивания
  chembl_target_id: "CHEMBL203"
  pubchem_accession: "P00533"


# ====== ОБУЧЕНИЕ ======

training:
  model_output_dir: "models/"
  test_size: 0.2
  n_trials_optuna: 200

  features:
    feature_type: "rdkit"  # "rdkit", "mordred", "morgan"  

    morgan:
      radius: 2
      n_bits: 2048

    corr_threshold: 0.7